FROM docker.io/python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir torch pyyaml --index-url https://download.pytorch.org/whl/cu121
COPY shakespeare_char.py /app/shakespeare_char.py
ENTRYPOINT ["python", "/app/shakespeare_char.py"]
